### ISSUE TITLE
GPU is not used

### ISSUE THREAD

**Issue by lyq1471** [Zhenye-Na/DA-RNN#5]
Thank you for your contribution, but I can't call GPU when I run this code. Here is my configuration.
Ubuntu18.04, CUDA9.0, cudnn7.0, pytorch0.3.0.

**Comment by Zhenye-Na** [comment]
Hi Michael,

Thank you for reaching out and I have read your email carefully.

As for your question of low usage of GPU, maybe I do not enable GPU support at that time. Would you go over the code in `model` or `training process` to test whether `cuda` has been enabled? Because unfortunately, back to that time when I implemented this paper, I do not have GPU environment to test performance by running on GPU.

I will try to refactor the codes in this repo later but will not be in a high priority. PR will be highly appreciated and welcomed! > <

Thanks for your understanding.

Best,
Zhenye

**Comment by lyq1471** [comment]
@Zhenye-Na 
Thank you very much for your reply. I am sure that CUDA is enabled. My variable output type is **“torch. cuda. FloatTensor of size *** (GPU 0)**. The **nividia-smi** shows that this process is taking up part of the GPU (about 768MB). In addition, **all variables are coded as CUDA in your code**, indicating that the code can also be applied to GPU. However, the highest GPU memory usage is about 9%, and the GPU utilization is about 25%. I still think it may be a Pytorch version problem or a delayed flow of data in a Class **(e.g. Class decoder or others)** of the model.

If there is the latest progress, I will explain it below in time. I hope you can find the problem . It's late in Beijing. I'm going to rest first. Thanks again. Night!
Best,
M. Liu

**Comment by Zhenye-Na** [comment]
Yes. I suggest using the latest version of torch.

Thanks for your help and I appreciate.

**Comment by lyq1471** [comment]
@Zhenye-Na 
I'm quite sure that my data is flowing in GPU, and all variable types are **torch.cuda.FloatTensor**. In  **Pytorch 1.0.1**, GPU memory usage also can't be improved, **very probably due to delays in data distribution**. My code is based on Chandler's blog in the Ref.

I run your code, which is only run on CPU. The problem is that the **train_forward** function in **model** does not put every batch variable into **cuda**. However, this can lead to some other problems.

**Comment by Zhenye-Na** [comment]
That is true! Back to the time when I started to implement this model. There is no GPU for me to test on and I do find several historical implementation drawbacks and bugs. Will fix it later. > <

Thanks in advance!

All the best.
